---
title: "EBDE Valeurs manquantes"
author: "Frédéric Bertrand"
date: "19 septembre 2024"
output: 
  github_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

***
️\ **Objectifs spécifiques**:

À la fin de ce chapitre, vous

- saurez comment procéder à l'imputation de valeurs manquantes en mode univarié et multivarié
- saurez comment détecter des valeurs aberrantes en mode univarié et multivarié

***

- Supports de cours. [Supports](Supports/MissingData_Aberration.html). [Code R](Supports/MissingData_Aberration.R). 

- Exemple de questions possibles sur le cours. [Questions types](Supports/ValeursManquante_Questions.html). 

- Script utilisé en cours [Script.R](Supports/Script.R) et le rapport html associé [Script.html](Supports/Script.html) 

- Feuille de calcul détaillant le calcul des règles de Rubin au format [.xlsx](Supports/Exemple_Regle_Rubin.xlsx), au format [.htm](Supports/Exemple_Regle_Rubin.htm) et au format [.pdf](Supports/Exemple_Regle_Rubin.pdf).







