---
title: "École doctorale : octobre 2024"
author: "Myriam Maumy et Frédéric Bertrand"
date: "25 octobre 2024"
output: 
  github_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

***
️\ **Objectifs spécifiques**:

À la fin de ce cours, vous

- saurez comment mettre en \oe uvre des tests non-paramétriques avec R
- saurez comment mettre en \oe uvre des tests de permutation avec R

***

- Supports de cours pour les tests non-paramétriques. 

    * Tests du signe, de Wilcoxon et de Mann et Whitney [Supports 1](Supports/Master1_Cours_NP_1.pdf). 
    
- Vers les tests de permutation. 

    * Exercice pratique [Partie 1](Supports/TD1_2ch.pdf) et [Partie 2](Supports/TD2_2chperm.pdf). 
    
    * Fragments de codes et éléments de solution des deux parties des exercices pratiques : Partie 1 [Partie 1](Supports/TD1_2ch_code_sol.html) et  [Partie 2](Supports/TD2_2chperm_code_sol.html). 
    
- Introduction au bootstrap. Test de permutation d'un coefficient de corrélation. [TD_bootstrap.html](Supports/TD_Bootstrap/TD_bootstrap.html)


- Applications interactives pour explorer les notions

    * Pour les [tests non-paramétriques](https://fbertran.shinyapps.io/nptests/)

    * Pour le [bootstrap](https://fbertran.shinyapps.io/shiny-bootstrap/)

    * Pour le [coefficient de corrélation bootstrap et permutation](https://fbertrand.shinyapps.io/Correlation_bootstrap_and_permutations/)



